// Generated by scripts/sync-exercise-media.mjs. Do not edit by hand.
import type { ExerciseMedia } from './exerciseMedia.ts'
export const EXERCISE_MEDIA: Readonly<Record<string, ExerciseMedia>> = {
  "barbell-bench": {
    "title": "Bench Press",
    "invert": false,
    "frames": [
      {
        "file": "everkinetic-0042-1.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0042-tension.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0042-tension.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      },
      {
        "file": "everkinetic-0042-2.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0042-relaxation.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0042-relaxation.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      }
    ]
  },
  "db-incline-press": {
    "title": "Dumbbell Incline Bench Press",
    "invert": false,
    "frames": [
      {
        "file": "everkinetic-0061-1.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0061-tension.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0061-tension.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      },
      {
        "file": "everkinetic-0061-2.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0061-relaxation.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0061-relaxation.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      }
    ]
  },
  "push-up": {
    "title": "Push Ups",
    "invert": false,
    "frames": [
      {
        "file": "everkinetic-0077-1.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0077-tension.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0077-tension.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      },
      {
        "file": "everkinetic-0077-2.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0077-relaxation.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0077-relaxation.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      }
    ]
  },
  "cable-row": {
    "title": "Seated Cable Rows",
    "invert": false,
    "frames": [
      {
        "file": "everkinetic-0025-1.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0025-tension.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0025-tension.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      },
      {
        "file": "everkinetic-0025-2.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0025-relaxation.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0025-relaxation.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      }
    ]
  },
  "lat-pulldown": {
    "title": "Wide Grip Lat Pull Down",
    "invert": false,
    "frames": [
      {
        "file": "everkinetic-0097-1.png",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/src/images-web/wide-grip-lat-pull-down-1.png",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/src/images-web/wide-grip-lat-pull-down-1.png",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      },
      {
        "file": "everkinetic-0097-2.png",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/src/images-web/wide-grip-lat-pull-down-2.png",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/src/images-web/wide-grip-lat-pull-down-2.png",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      }
    ]
  },
  "barbell-row": {
    "title": "Barbell Row",
    "invert": true,
    "frames": [
      {
        "file": "guide-barbell-row-1.svg",
        "url": "https://raw.githubusercontent.com/bryllim/workout-guide/aac599224bb9780305239607ef98540b7e0ce389/packages/workout-guide/assets/barbell-row/frame-1.svg",
        "sourceUrl": "https://github.com/bryllim/workout-guide/blob/aac599224bb9780305239607ef98540b7e0ce389/packages/workout-guide/assets/barbell-row/frame-1.svg",
        "creator": "Bryl Lim",
        "creatorUrl": "https://bryllim.com",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato. Colori invertiti solo nella visualizzazione.",
        "original": {
          "name": "Everkinetic",
          "url": "https://github.com/everkinetic/data/blob/main/dist/svg/0026-tension.svg",
          "license": "CC BY-SA 4.0",
          "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
          "changes": "Rasterized on a transparent 512 × 512 canvas, recolored for monochrome display, and vector-traced."
        }
      }
    ]
  },
  "db-row": {
    "title": "Dumbbell Bent Over Row",
    "invert": true,
    "frames": [
      {
        "file": "guide-dumbbell-bent-over-row-1.svg",
        "url": "https://raw.githubusercontent.com/bryllim/workout-guide/aac599224bb9780305239607ef98540b7e0ce389/packages/workout-guide/assets/dumbbell-bent-over-row/frame-1.svg",
        "sourceUrl": "https://github.com/bryllim/workout-guide/blob/aac599224bb9780305239607ef98540b7e0ce389/packages/workout-guide/assets/dumbbell-bent-over-row/frame-1.svg",
        "creator": "Bryl Lim",
        "creatorUrl": "https://bryllim.com",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato. Colori invertiti solo nella visualizzazione."
      }
    ]
  },
  "barbell-overhead-press": {
    "title": "Overhead Press",
    "invert": true,
    "frames": [
      {
        "file": "guide-overhead-press-1.svg",
        "url": "https://raw.githubusercontent.com/bryllim/workout-guide/aac599224bb9780305239607ef98540b7e0ce389/packages/workout-guide/assets/overhead-press/frame-1.svg",
        "sourceUrl": "https://github.com/bryllim/workout-guide/blob/aac599224bb9780305239607ef98540b7e0ce389/packages/workout-guide/assets/overhead-press/frame-1.svg",
        "creator": "Bryl Lim",
        "creatorUrl": "https://bryllim.com",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato. Colori invertiti solo nella visualizzazione."
      }
    ]
  },
  "db-overhead-press": {
    "title": "Standing Dumbbell Press",
    "invert": true,
    "frames": [
      {
        "file": "guide-standing-dumbbell-press-1.svg",
        "url": "https://raw.githubusercontent.com/bryllim/workout-guide/aac599224bb9780305239607ef98540b7e0ce389/packages/workout-guide/assets/standing-dumbbell-press/frame-1.svg",
        "sourceUrl": "https://github.com/bryllim/workout-guide/blob/aac599224bb9780305239607ef98540b7e0ce389/packages/workout-guide/assets/standing-dumbbell-press/frame-1.svg",
        "creator": "Bryl Lim",
        "creatorUrl": "https://bryllim.com",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato. Colori invertiti solo nella visualizzazione."
      }
    ]
  },
  "pike-push-up": {
    "title": "Pike Push-up",
    "invert": true,
    "frames": [
      {
        "file": "guide-pike-push-up-1.svg",
        "url": "https://raw.githubusercontent.com/bryllim/workout-guide/aac599224bb9780305239607ef98540b7e0ce389/packages/workout-guide/assets/pike-push-up/frame-1.svg",
        "sourceUrl": "https://github.com/bryllim/workout-guide/blob/aac599224bb9780305239607ef98540b7e0ce389/packages/workout-guide/assets/pike-push-up/frame-1.svg",
        "creator": "Bryl Lim",
        "creatorUrl": "https://bryllim.com",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato. Colori invertiti solo nella visualizzazione."
      }
    ]
  },
  "db-lateral-raise": {
    "title": "Lateral Dumbbell Raises",
    "invert": false,
    "frames": [
      {
        "file": "everkinetic-0018-1.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0018-tension.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0018-tension.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      },
      {
        "file": "everkinetic-0018-2.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0018-relaxation.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0018-relaxation.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      }
    ]
  },
  "barbell-squat": {
    "title": "Barbell Squat",
    "invert": false,
    "frames": [
      {
        "file": "everkinetic-0122-1.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0122-tension.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0122-tension.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      },
      {
        "file": "everkinetic-0122-2.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0122-relaxation.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0122-relaxation.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      }
    ]
  },
  "db-goblet-squat": {
    "title": "Goblet Squat",
    "invert": true,
    "frames": [
      {
        "file": "guide-goblet-squat-1.svg",
        "url": "https://raw.githubusercontent.com/bryllim/workout-guide/aac599224bb9780305239607ef98540b7e0ce389/packages/workout-guide/assets/goblet-squat/frame-1.svg",
        "sourceUrl": "https://github.com/bryllim/workout-guide/blob/aac599224bb9780305239607ef98540b7e0ce389/packages/workout-guide/assets/goblet-squat/frame-1.svg",
        "creator": "Bryl Lim",
        "creatorUrl": "https://bryllim.com",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato. Colori invertiti solo nella visualizzazione."
      }
    ]
  },
  "db-reverse-lunge": {
    "title": "Rear Lunges with Dumbbell",
    "invert": false,
    "frames": [
      {
        "file": "everkinetic-0129-1.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0129-tension.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0129-tension.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      },
      {
        "file": "everkinetic-0129-2.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0129-relaxation.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0129-relaxation.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      }
    ]
  },
  "bodyweight-squat": {
    "title": "Bodyweight Squat",
    "invert": true,
    "frames": [
      {
        "file": "guide-bodyweight-squat-1.svg",
        "url": "https://raw.githubusercontent.com/bryllim/workout-guide/aac599224bb9780305239607ef98540b7e0ce389/packages/workout-guide/assets/bodyweight-squat/frame-1.svg",
        "sourceUrl": "https://github.com/bryllim/workout-guide/blob/aac599224bb9780305239607ef98540b7e0ce389/packages/workout-guide/assets/bodyweight-squat/frame-1.svg",
        "creator": "Bryl Lim",
        "creatorUrl": "https://bryllim.com",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato. Colori invertiti solo nella visualizzazione."
      }
    ]
  },
  "barbell-hip-thrust": {
    "title": "Hip Thrust",
    "invert": true,
    "frames": [
      {
        "file": "guide-hip-thrust-1.svg",
        "url": "https://raw.githubusercontent.com/bryllim/workout-guide/aac599224bb9780305239607ef98540b7e0ce389/packages/workout-guide/assets/hip-thrust/frame-1.svg",
        "sourceUrl": "https://github.com/bryllim/workout-guide/blob/aac599224bb9780305239607ef98540b7e0ce389/packages/workout-guide/assets/hip-thrust/frame-1.svg",
        "creator": "Bryl Lim",
        "creatorUrl": "https://bryllim.com",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato. Colori invertiti solo nella visualizzazione."
      }
    ]
  },
  "db-glute-bridge": {
    "title": "Dumbbell Glute Bridge",
    "invert": true,
    "frames": [
      {
        "file": "guide-dumbbell-glute-bridge-1.svg",
        "url": "https://raw.githubusercontent.com/bryllim/workout-guide/aac599224bb9780305239607ef98540b7e0ce389/packages/workout-guide/assets/dumbbell-glute-bridge/frame-1.svg",
        "sourceUrl": "https://github.com/bryllim/workout-guide/blob/aac599224bb9780305239607ef98540b7e0ce389/packages/workout-guide/assets/dumbbell-glute-bridge/frame-1.svg",
        "creator": "Bryl Lim",
        "creatorUrl": "https://bryllim.com",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato. Colori invertiti solo nella visualizzazione."
      }
    ]
  },
  "single-leg-bridge": {
    "title": "Single-Leg Glute Bridge",
    "invert": true,
    "frames": [
      {
        "file": "guide-single-leg-glute-bridge-1.svg",
        "url": "https://raw.githubusercontent.com/bryllim/workout-guide/aac599224bb9780305239607ef98540b7e0ce389/packages/workout-guide/assets/single-leg-glute-bridge/frame-1.svg",
        "sourceUrl": "https://github.com/bryllim/workout-guide/blob/aac599224bb9780305239607ef98540b7e0ce389/packages/workout-guide/assets/single-leg-glute-bridge/frame-1.svg",
        "creator": "Bryl Lim",
        "creatorUrl": "https://bryllim.com",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato. Colori invertiti solo nella visualizzazione."
      }
    ]
  },
  "barbell-rdl": {
    "title": "Romanian Dead Lift",
    "invert": false,
    "frames": [
      {
        "file": "everkinetic-0118-1.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0118-tension.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0118-tension.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      },
      {
        "file": "everkinetic-0118-2.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0118-relaxation.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0118-relaxation.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      }
    ]
  },
  "db-rdl": {
    "title": "Dumbbell Romanian Deadlift",
    "invert": true,
    "frames": [
      {
        "file": "guide-dumbbell-romanian-deadlift-1.svg",
        "url": "https://raw.githubusercontent.com/bryllim/workout-guide/aac599224bb9780305239607ef98540b7e0ce389/packages/workout-guide/assets/dumbbell-romanian-deadlift/frame-1.svg",
        "sourceUrl": "https://github.com/bryllim/workout-guide/blob/aac599224bb9780305239607ef98540b7e0ce389/packages/workout-guide/assets/dumbbell-romanian-deadlift/frame-1.svg",
        "creator": "Bryl Lim",
        "creatorUrl": "https://bryllim.com",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato. Colori invertiti solo nella visualizzazione."
      }
    ]
  },
  "db-curl": {
    "title": "Biceps Curl with Dumbbell",
    "invert": false,
    "frames": [
      {
        "file": "everkinetic-0224-1.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0224-tension.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0224-tension.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      },
      {
        "file": "everkinetic-0224-2.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0224-relaxation.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0224-relaxation.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      }
    ]
  },
  "cable-triceps": {
    "title": "Triceps Pushdown with Rope and Cable",
    "invert": false,
    "frames": [
      {
        "file": "everkinetic-0206-1.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0206-tension.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0206-tension.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      },
      {
        "file": "everkinetic-0206-2.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0206-relaxation.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0206-relaxation.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      }
    ]
  },
  "db-triceps-extension": {
    "title": "Standing Triceps Extension",
    "invert": false,
    "frames": [
      {
        "file": "everkinetic-0167-1.png",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/src/images-web/standing-triceps-extension-1.png",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/src/images-web/standing-triceps-extension-1.png",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      },
      {
        "file": "everkinetic-0167-2.png",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/src/images-web/standing-triceps-extension-2.png",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/src/images-web/standing-triceps-extension-2.png",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      }
    ]
  },
  "db-hammer-curl": {
    "title": "Biceps Hammer Curl with Dumbbell",
    "invert": false,
    "frames": [
      {
        "file": "everkinetic-0227-1.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0227-tension.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0227-tension.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      },
      {
        "file": "everkinetic-0227-2.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0227-relaxation.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0227-relaxation.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      }
    ]
  },
  "dead-bug": {
    "title": "Dead Bug",
    "invert": true,
    "frames": [
      {
        "file": "guide-dead-bug-1.svg",
        "url": "https://raw.githubusercontent.com/bryllim/workout-guide/aac599224bb9780305239607ef98540b7e0ce389/packages/workout-guide/assets/dead-bug/frame-1.svg",
        "sourceUrl": "https://github.com/bryllim/workout-guide/blob/aac599224bb9780305239607ef98540b7e0ce389/packages/workout-guide/assets/dead-bug/frame-1.svg",
        "creator": "Bryl Lim",
        "creatorUrl": "https://bryllim.com",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato. Colori invertiti solo nella visualizzazione."
      }
    ]
  },
  "reverse-crunch": {
    "title": "Bent Knee Hip Raise",
    "invert": false,
    "frames": [
      {
        "file": "everkinetic-0287-1.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0287-tension.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0287-tension.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      },
      {
        "file": "everkinetic-0287-2.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0287-relaxation.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0287-relaxation.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      }
    ]
  },
  "bird-dog": {
    "title": "Bird Dog",
    "invert": true,
    "frames": [
      {
        "file": "guide-bird-dog-1.svg",
        "url": "https://raw.githubusercontent.com/bryllim/workout-guide/aac599224bb9780305239607ef98540b7e0ce389/packages/workout-guide/assets/bird-dog/frame-1.svg",
        "sourceUrl": "https://github.com/bryllim/workout-guide/blob/aac599224bb9780305239607ef98540b7e0ce389/packages/workout-guide/assets/bird-dog/frame-1.svg",
        "creator": "Bryl Lim",
        "creatorUrl": "https://bryllim.com",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato. Colori invertiti solo nella visualizzazione."
      }
    ]
  },
  "leg-press": {
    "title": "Leg Press",
    "invert": false,
    "frames": [
      {
        "file": "everkinetic-0127-1.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0127-tension.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0127-tension.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      },
      {
        "file": "everkinetic-0127-2.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0127-relaxation.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0127-relaxation.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      }
    ]
  },
  "cable-fly": {
    "title": "Cable Crossover",
    "invert": false,
    "frames": [
      {
        "file": "everkinetic-0048-1.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0048-tension.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0048-tension.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      },
      {
        "file": "everkinetic-0048-2.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0048-relaxation.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0048-relaxation.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      }
    ]
  },
  "pull-up": {
    "title": "Pull Ups",
    "invert": false,
    "frames": [
      {
        "file": "everkinetic-0087-1.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0087-tension.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0087-tension.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      },
      {
        "file": "everkinetic-0087-2.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0087-relaxation.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0087-relaxation.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      }
    ]
  },
  "db-flat-bench-press": {
    "title": "Bench Press Dumbbell",
    "invert": false,
    "frames": [
      {
        "file": "everkinetic-0055-1.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0055-tension.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0055-tension.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      },
      {
        "file": "everkinetic-0055-2.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0055-relaxation.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0055-relaxation.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      }
    ]
  },
  "close-grip-lat-pulldown": {
    "title": "V Bar Pull Down",
    "invert": false,
    "frames": [
      {
        "file": "everkinetic-0096-1.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0096-tension.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0096-tension.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      },
      {
        "file": "everkinetic-0096-2.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0096-relaxation.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0096-relaxation.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      }
    ]
  },
  "chest-dip": {
    "title": "Chest Dips",
    "invert": false,
    "frames": [
      {
        "file": "everkinetic-0054-1.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0054-tension.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0054-tension.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      },
      {
        "file": "everkinetic-0054-2.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0054-relaxation.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0054-relaxation.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      }
    ]
  },
  "cable-preacher-curl": {
    "title": "Preacher Curl with Cable",
    "invert": false,
    "frames": [
      {
        "file": "everkinetic-0217-1.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0217-tension.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0217-tension.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      },
      {
        "file": "everkinetic-0217-2.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0217-relaxation.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0217-relaxation.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      }
    ]
  },
  "db-preacher-curl": {
    "title": "One Arm Preacher Curl with Dumbbell",
    "invert": false,
    "frames": [
      {
        "file": "everkinetic-0237-1.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0237-tension.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0237-tension.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      },
      {
        "file": "everkinetic-0237-2.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0237-relaxation.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0237-relaxation.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      }
    ]
  },
  "leg-extension": {
    "title": "Leg Extensions",
    "invert": false,
    "frames": [
      {
        "file": "everkinetic-0142-1.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0142-tension.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0142-tension.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      },
      {
        "file": "everkinetic-0142-2.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0142-relaxation.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0142-relaxation.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      }
    ]
  },
  "seated-leg-curl": {
    "title": "Seated Leg Curl",
    "invert": false,
    "frames": [
      {
        "file": "everkinetic-0119-1.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0119-tension.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0119-tension.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      },
      {
        "file": "everkinetic-0119-2.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0119-relaxation.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0119-relaxation.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      }
    ]
  },
  "cable-straight-arm-pulldown": {
    "title": "Straight Arm Push Down",
    "invert": false,
    "frames": [
      {
        "file": "everkinetic-0092-1.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0092-tension.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0092-tension.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      },
      {
        "file": "everkinetic-0092-2.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0092-relaxation.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0092-relaxation.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      }
    ]
  },
  "db-reverse-fly": {
    "title": "Rear Delt Fly",
    "invert": true,
    "frames": [
      {
        "file": "guide-rear-delt-fly-1.svg",
        "url": "https://raw.githubusercontent.com/bryllim/workout-guide/aac599224bb9780305239607ef98540b7e0ce389/packages/workout-guide/assets/rear-delt-fly/frame-1.svg",
        "sourceUrl": "https://github.com/bryllim/workout-guide/blob/aac599224bb9780305239607ef98540b7e0ce389/packages/workout-guide/assets/rear-delt-fly/frame-1.svg",
        "creator": "Bryl Lim",
        "creatorUrl": "https://bryllim.com",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato. Colori invertiti solo nella visualizzazione."
      }
    ]
  },
  "machine-chest-press": {
    "title": "Machine Bench Press",
    "invert": false,
    "frames": [
      {
        "file": "everkinetic-0066-1.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0066-tension.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0066-tension.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      },
      {
        "file": "everkinetic-0066-2.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0066-relaxation.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0066-relaxation.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      }
    ]
  },
  "machine-decline-chest-press": {
    "title": "Decline Chest Press",
    "invert": false,
    "frames": [
      {
        "file": "everkinetic-0085-1.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0085-tension.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0085-tension.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      },
      {
        "file": "everkinetic-0085-2.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0085-relaxation.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0085-relaxation.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      }
    ]
  },
  "barbell-incline-bench": {
    "title": "Incline Bench Press",
    "invert": false,
    "frames": [
      {
        "file": "everkinetic-0043-1.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0043-tension.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0043-tension.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      },
      {
        "file": "everkinetic-0043-2.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0043-relaxation.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0043-relaxation.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      }
    ]
  },
  "db-bench-fly": {
    "title": "Dumbbell Flys",
    "invert": false,
    "frames": [
      {
        "file": "everkinetic-0056-1.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0056-tension.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0056-tension.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      },
      {
        "file": "everkinetic-0056-2.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0056-relaxation.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0056-relaxation.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      }
    ]
  },
  "machine-chest-fly": {
    "title": "Butterfly Machine",
    "invert": false,
    "frames": [
      {
        "file": "everkinetic-0047-1.png",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/src/images-web/butterfly-machine-1.png",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/src/images-web/butterfly-machine-1.png",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      },
      {
        "file": "everkinetic-0047-2.png",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/src/images-web/butterfly-machine-2.png",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/src/images-web/butterfly-machine-2.png",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      }
    ]
  },
  "t-bar-row": {
    "title": "T-Bar Rows",
    "invert": false,
    "frames": [
      {
        "file": "everkinetic-0029-1.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0029-tension.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0029-tension.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      },
      {
        "file": "everkinetic-0029-2.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0029-relaxation.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0029-relaxation.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      }
    ]
  },
  "cable-row-v-grip": {
    "title": "Seated Cable Rows",
    "invert": false,
    "frames": [
      {
        "file": "everkinetic-0025-1.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0025-tension.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0025-tension.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      },
      {
        "file": "everkinetic-0025-2.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0025-relaxation.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0025-relaxation.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      }
    ]
  },
  "machine-seated-row": {
    "title": "Machine Row",
    "invert": true,
    "frames": [
      {
        "file": "guide-machine-row-1.svg",
        "url": "https://raw.githubusercontent.com/bryllim/workout-guide/aac599224bb9780305239607ef98540b7e0ce389/packages/workout-guide/assets/machine-row/frame-1.svg",
        "sourceUrl": "https://github.com/bryllim/workout-guide/blob/aac599224bb9780305239607ef98540b7e0ce389/packages/workout-guide/assets/machine-row/frame-1.svg",
        "creator": "Bryl Lim",
        "creatorUrl": "https://bryllim.com",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato. Colori invertiti solo nella visualizzazione."
      }
    ]
  },
  "machine-hack-squat": {
    "title": "Hack Squat Machine",
    "invert": false,
    "frames": [
      {
        "file": "everkinetic-0123-1.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0123-tension.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0123-tension.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      },
      {
        "file": "everkinetic-0123-2.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0123-relaxation.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0123-relaxation.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      }
    ]
  },
  "db-curtsy-lunge": {
    "title": "Dumbbell Curtsy Lunge",
    "invert": true,
    "frames": [
      {
        "file": "guide-dumbbell-curtsy-lunge-1.svg",
        "url": "https://raw.githubusercontent.com/bryllim/workout-guide/aac599224bb9780305239607ef98540b7e0ce389/packages/workout-guide/assets/dumbbell-curtsy-lunge/frame-1.svg",
        "sourceUrl": "https://github.com/bryllim/workout-guide/blob/aac599224bb9780305239607ef98540b7e0ce389/packages/workout-guide/assets/dumbbell-curtsy-lunge/frame-1.svg",
        "creator": "Bryl Lim",
        "creatorUrl": "https://bryllim.com",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato. Colori invertiti solo nella visualizzazione."
      }
    ]
  },
  "machine-lying-leg-curl": {
    "title": "Lying Leg Curl Machine",
    "invert": false,
    "frames": [
      {
        "file": "everkinetic-0117-1.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0117-tension.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0117-tension.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      },
      {
        "file": "everkinetic-0117-2.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0117-relaxation.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0117-relaxation.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      }
    ]
  },
  "standing-leg-curl": {
    "title": "Standing Leg Curls",
    "invert": false,
    "frames": [
      {
        "file": "everkinetic-0120-1.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0120-tension.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0120-tension.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      },
      {
        "file": "everkinetic-0120-2.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0120-relaxation.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0120-relaxation.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      }
    ]
  },
  "db-arnold-press": {
    "title": "Arnold Press",
    "invert": false,
    "frames": [
      {
        "file": "everkinetic-0006-1.png",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/src/images-web/arnold-press-1.png",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/src/images-web/arnold-press-1.png",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      },
      {
        "file": "everkinetic-0006-2.png",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/src/images-web/arnold-press-2.png",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/src/images-web/arnold-press-2.png",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      }
    ]
  },
  "cable-face-pull": {
    "title": "Face Pull",
    "invert": true,
    "frames": [
      {
        "file": "guide-face-pull-1.svg",
        "url": "https://raw.githubusercontent.com/bryllim/workout-guide/aac599224bb9780305239607ef98540b7e0ce389/packages/workout-guide/assets/face-pull/frame-1.svg",
        "sourceUrl": "https://github.com/bryllim/workout-guide/blob/aac599224bb9780305239607ef98540b7e0ce389/packages/workout-guide/assets/face-pull/frame-1.svg",
        "creator": "Bryl Lim",
        "creatorUrl": "https://bryllim.com",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato. Colori invertiti solo nella visualizzazione."
      }
    ]
  },
  "db-incline-curl": {
    "title": "Alternating Incline Curl with Dumbbell",
    "invert": false,
    "frames": [
      {
        "file": "everkinetic-0214-1.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0214-tension.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0214-tension.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      },
      {
        "file": "everkinetic-0214-2.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0214-relaxation.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0214-relaxation.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      }
    ]
  },
  "concentration-curl": {
    "title": "Concentration Curls with Dumbbell",
    "invert": false,
    "frames": [
      {
        "file": "everkinetic-0220-1.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0220-tension.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0220-tension.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      },
      {
        "file": "everkinetic-0220-2.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0220-relaxation.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0220-relaxation.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      }
    ]
  },
  "db-spider-curl": {
    "title": "Prone Incline Biceps Curl with Dumbbell",
    "invert": false,
    "frames": [
      {
        "file": "everkinetic-0225-1.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0225-tension.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0225-tension.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      },
      {
        "file": "everkinetic-0225-2.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0225-relaxation.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0225-relaxation.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      }
    ]
  },
  "cable-overhead-triceps": {
    "title": "Overhead Tricep Extension",
    "invert": true,
    "frames": [
      {
        "file": "guide-overhead-tricep-extension-1.svg",
        "url": "https://raw.githubusercontent.com/bryllim/workout-guide/aac599224bb9780305239607ef98540b7e0ce389/packages/workout-guide/assets/overhead-tricep-extension/frame-1.svg",
        "sourceUrl": "https://github.com/bryllim/workout-guide/blob/aac599224bb9780305239607ef98540b7e0ce389/packages/workout-guide/assets/overhead-tricep-extension/frame-1.svg",
        "creator": "Bryl Lim",
        "creatorUrl": "https://bryllim.com",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato. Colori invertiti solo nella visualizzazione."
      }
    ]
  },
  "db-skullcrusher": {
    "title": "Lying Triceps Extension with Dumbbells",
    "invert": false,
    "frames": [
      {
        "file": "everkinetic-0181-1.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0181-tension.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0181-tension.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      },
      {
        "file": "everkinetic-0181-2.svg",
        "url": "https://raw.githubusercontent.com/everkinetic/data/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0181-relaxation.svg",
        "sourceUrl": "https://github.com/everkinetic/data/blob/446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6/dist/svg/0181-relaxation.svg",
        "creator": "Everkinetic / Greg Priday",
        "creatorUrl": "https://github.com/everkinetic/data",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato."
      }
    ]
  },
  "db-single-arm-triceps-extension": {
    "title": "Single Arm Dumbbell Tricep Extension",
    "invert": true,
    "frames": [
      {
        "file": "guide-single-arm-dumbbell-tricep-extension-1.svg",
        "url": "https://raw.githubusercontent.com/bryllim/workout-guide/aac599224bb9780305239607ef98540b7e0ce389/packages/workout-guide/assets/single-arm-dumbbell-tricep-extension/frame-1.svg",
        "sourceUrl": "https://github.com/bryllim/workout-guide/blob/aac599224bb9780305239607ef98540b7e0ce389/packages/workout-guide/assets/single-arm-dumbbell-tricep-extension/frame-1.svg",
        "creator": "Bryl Lim",
        "creatorUrl": "https://bryllim.com",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
        "changes": "File originale, non modificato. Colori invertiti solo nella visualizzazione."
      }
    ]
  }
}
