export const MEDIA_REVISIONS = {
  everkinetic: '446bb9a3d0c3beb6b84f7c9d77dfc8af707a2ab6',
  guide: 'aac599224bb9780305239607ef98540b7e0ce389',
} as const

export type MediaSource = { provider: 'everkinetic' | 'guide'; id: string }

// Deliberate, variant-specific associations. Missing variants must not inherit
// an image from their muscle group, movement pattern, or CSV classification base.
export const MEDIA_SOURCES: Readonly<Record<string, MediaSource>> = {
  'barbell-bench': { provider: 'everkinetic', id: '0042' },
  'db-incline-press': { provider: 'everkinetic', id: '0061' },
  'push-up': { provider: 'everkinetic', id: '0077' },
  'cable-row': { provider: 'everkinetic', id: '0025' },
  'lat-pulldown': { provider: 'everkinetic', id: '0097' },
  'barbell-row': { provider: 'guide', id: 'barbell-row' },
  'db-row': { provider: 'guide', id: 'dumbbell-bent-over-row' },
  'barbell-overhead-press': { provider: 'guide', id: 'overhead-press' },
  'db-overhead-press': { provider: 'guide', id: 'standing-dumbbell-press' },
  'pike-push-up': { provider: 'guide', id: 'pike-push-up' },
  'db-lateral-raise': { provider: 'everkinetic', id: '0018' },
  'barbell-squat': { provider: 'everkinetic', id: '0122' },
  'db-goblet-squat': { provider: 'guide', id: 'goblet-squat' },
  'db-reverse-lunge': { provider: 'everkinetic', id: '0129' },
  'bodyweight-squat': { provider: 'guide', id: 'bodyweight-squat' },
  'barbell-hip-thrust': { provider: 'guide', id: 'hip-thrust' },
  'db-glute-bridge': { provider: 'guide', id: 'dumbbell-glute-bridge' },
  'single-leg-bridge': { provider: 'guide', id: 'single-leg-glute-bridge' },
  'barbell-rdl': { provider: 'everkinetic', id: '0118' },
  'db-rdl': { provider: 'guide', id: 'dumbbell-romanian-deadlift' },
  'db-curl': { provider: 'everkinetic', id: '0224' },
  'cable-triceps': { provider: 'everkinetic', id: '0206' },
  'db-triceps-extension': { provider: 'everkinetic', id: '0167' },
  'db-hammer-curl': { provider: 'everkinetic', id: '0227' },
  'dead-bug': { provider: 'guide', id: 'dead-bug' },
  'reverse-crunch': { provider: 'everkinetic', id: '0287' },
  'bird-dog': { provider: 'guide', id: 'bird-dog' },
  'leg-press': { provider: 'everkinetic', id: '0127' },
  'cable-fly': { provider: 'everkinetic', id: '0048' },
  'pull-up': { provider: 'everkinetic', id: '0087' },
  'db-flat-bench-press': { provider: 'everkinetic', id: '0055' },
  'close-grip-lat-pulldown': { provider: 'everkinetic', id: '0096' },
  'chest-dip': { provider: 'everkinetic', id: '0054' },
  'cable-preacher-curl': { provider: 'everkinetic', id: '0217' },
  'db-preacher-curl': { provider: 'everkinetic', id: '0237' },
  'leg-extension': { provider: 'everkinetic', id: '0142' },
  'seated-leg-curl': { provider: 'everkinetic', id: '0119' },
  'cable-straight-arm-pulldown': { provider: 'everkinetic', id: '0092' },
  'db-reverse-fly': { provider: 'guide', id: 'rear-delt-fly' },
  'machine-chest-press': { provider: 'everkinetic', id: '0066' },
  'machine-decline-chest-press': { provider: 'everkinetic', id: '0085' },
  'barbell-incline-bench': { provider: 'everkinetic', id: '0043' },
  'db-bench-fly': { provider: 'everkinetic', id: '0056' },
  'machine-chest-fly': { provider: 'everkinetic', id: '0047' },
  't-bar-row': { provider: 'everkinetic', id: '0029' },
  'cable-row-v-grip': { provider: 'everkinetic', id: '0025' },
  'machine-seated-row': { provider: 'guide', id: 'machine-row' },
  'machine-hack-squat': { provider: 'everkinetic', id: '0123' },
  'db-curtsy-lunge': { provider: 'guide', id: 'dumbbell-curtsy-lunge' },
  'machine-lying-leg-curl': { provider: 'everkinetic', id: '0117' },
  'standing-leg-curl': { provider: 'everkinetic', id: '0120' },
  'db-arnold-press': { provider: 'everkinetic', id: '0006' },
  'cable-face-pull': { provider: 'guide', id: 'face-pull' },
  'db-incline-curl': { provider: 'everkinetic', id: '0214' },
  'concentration-curl': { provider: 'everkinetic', id: '0220' },
  'db-spider-curl': { provider: 'everkinetic', id: '0225' },
  'cable-overhead-triceps': { provider: 'guide', id: 'overhead-tricep-extension' },
  'db-skullcrusher': { provider: 'everkinetic', id: '0181' },
  'db-single-arm-triceps-extension': { provider: 'guide', id: 'single-arm-dumbbell-tricep-extension' },
}
